<?php
/**
 * Create New User Account
 * Path: modules/settings/user-add.php
 */
require_once '../../config/config.php';
require_once '../../includes/session-manager.php';

$authUser->requirePermission('system_admin');

$db = Database::getInstance();
$errors = [];
$success = false;

// Initialize form values to retain state
$employeeId = '';
$username = '';
$email = '';
$firstName = '';
$lastName = '';
$middleName = '';
$phone = '';
$department = '';
$role = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!validateCsrfToken($_POST['csrf_token'] ?? '')) {
        $errors[] = 'Invalid security token.';
    } else {
        // Trim and sanitize all inputs
        $employeeId = trim($_POST['employee_id'] ?? '');
        $username = trim($_POST['username'] ?? '');
        $email = trim($_POST['email'] ?? '');
        $password = $_POST['password'] ?? ''; 
        $passwordConfirm = $_POST['confirm_password'] ?? '';
        $firstName = trim($_POST['first_name'] ?? '');
        $lastName = trim($_POST['last_name'] ?? '');
        $middleName = trim($_POST['middle_name'] ?? '');
        $phone = trim($_POST['phone'] ?? '');
        $department = trim($_POST['department'] ?? '');
        $role = trim($_POST['role'] ?? '');

        $allowedDepts = ['admin', 'management', 'operations', 'maintenance', 'procurement', 'customer_service'];
        $allowedRoles = ['system_admin', 'fleet_manager', 'procurement_officer', 'maintenance_supervisor', 'customer_service_staff', 'mechanic', 'viewer', 'qr_scanner'];

        // Server-side validation
        if (!$employeeId || !$username || !$firstName || !$lastName || !$password || !$passwordConfirm || !$email || !$department || !$role) {
            $errors[] = 'All required fields must be filled in.';
        } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $errors[] = 'Please enter a valid email address.';
        } elseif (strlen($password) < 8) {
            $errors[] = 'Password must be at least 8 characters long.';
        } elseif ($password !== $passwordConfirm) {
            $errors[] = 'Passwords do not match.';
        } elseif (!in_array($department, $allowedDepts, true)) {
            $errors[] = 'Invalid department selected.';
        } elseif (!in_array($role, $allowedRoles, true)) {
            $errors[] = 'Invalid role selected.';
        } else {
            $userObj = new User();
            try {
                $data = [
                    'employee_id' => $employeeId,
                    'username' => $username,
                    'email' => $email,
                    'password' => $password,
                    'first_name' => $firstName,
                    'last_name' => $lastName,
                    'middle_name' => $middleName ?: null,
                    'phone' => $phone ?: null,
                    'department' => $department,
                    'role' => $role,
                    'must_change_password' => isset($_POST['must_change'])
                ];

                $userObj->create($data, $_SESSION['user_id']);

                $_SESSION['success_message'] = 'Account created successfully for ' . htmlspecialchars($firstName . ' ' . $lastName);
                header('Location: user-management.php');
                exit;

            } catch (Exception $e) {
                error_log('User create error by user_id ' . $_SESSION['user_id'] . ': ' . $e->getMessage());
                // Display the specific error message generated by the User class validation
                $errors[] = $e->getMessage();
            }
        }
    }
}

$pageTitle = 'Create Account';
require_once '../../includes/header.php';
?>

<div class="page-header">
    <div class="page-title">
        <h1>Create Account</h1>
        <p>Onboard a new system user and define their access level.</p>
    </div>
</div>

<div class="card card-form-centered">
    <?php if (!empty($errors)): ?>
        <div class="card-body" style="padding-bottom: 0;">
            <div class="form-error-alert">
                <strong>Error:</strong> <?= htmlspecialchars($errors[0]) ?>
            </div>
        </div>
    <?php endif; ?>

    <form method="POST">
        <?= csrfField() ?>
        <div class="card-body">
            <div class="form-grid form-grid--two">
                <div class="form-group">
                    <label for="employee_id">Employee ID <span class="text-danger">*</span></label>
                    <div style="display:flex; gap:8px;">
                        <input type="text" class="form-control" name="employee_id" id="employee_id" required
                            placeholder="e.g. EMP-2024-001" style="font-family:monospace; text-transform:uppercase;"
                            value="<?= htmlspecialchars($employeeId) ?>">
                        <button type="button" class="btn btn-secondary" onclick="generateEmployeeId()" style="white-space:nowrap; padding:0 12px; font-size:0.8125rem;">
                            <i data-lucide="zap" style="width:14px;height:14px;margin-right:4px;"></i> Auto
                        </button>
                    </div>
                </div>
                <div class="form-group">
                    <label for="username">Username <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="username" id="username" required
                        value="<?= htmlspecialchars($username) ?>">
                </div>

                <div class="form-group">
                    <label for="first_name">First Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="first_name" id="first_name" required
                        value="<?= htmlspecialchars($firstName) ?>">
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="last_name" id="last_name" required
                        value="<?= htmlspecialchars($lastName) ?>">
                </div>

                <div class="form-group">
                    <label for="middle_name">Middle Name (Optional)</label>
                    <input type="text" class="form-control" name="middle_name" id="middle_name"
                        value="<?= htmlspecialchars($middleName) ?>">
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number (Optional)</label>
                    <input type="text" class="form-control" name="phone" id="phone"
                        value="<?= htmlspecialchars($phone) ?>">
                </div>

                <div class="form-group" style="grid-column: 1 / -1;">
                    <label for="email">Email Address <span class="text-danger">*</span></label>
                    <input type="email" class="form-control" name="email" id="email" required
                        value="<?= htmlspecialchars($email) ?>">
                </div>

                <div class="form-group">
                    <label for="password">Temporary Password <span class="text-danger">*</span></label>
                    <div style="position:relative;">
                        <input type="password" class="form-control" name="password" id="password" required>
                        <button type="button" onclick="togglePassword('password', 'pToggle1')"
                            style="position:absolute;right:12px;top:50%;transform:translateY(-50%);background:none;border:none;color:var(--text-muted);cursor:pointer;padding:4px;">
                            <i id="pToggle1" data-lucide="eye" style="width:20px;height:20px;"></i>
                        </button>
                    </div>
                </div>
                <div class="form-group">
                    <label for="confirm_password">Confirm Password <span class="text-danger">*</span></label>
                    <div style="position:relative;">
                        <input type="password" class="form-control" name="confirm_password" id="confirm_password" required>
                        <button type="button" onclick="togglePassword('confirm_password', 'pToggle2')"
                            style="position:absolute;right:12px;top:50%;transform:translateY(-50%);background:none;border:none;color:var(--text-muted);cursor:pointer;padding:4px;">
                            <i id="pToggle2" data-lucide="eye" style="width:20px;height:20px;"></i>
                        </button>
                    </div>
                </div>

                <div class="form-group">
                    <label for="department">Department <span class="text-danger">*</span></label>
                    <select name="department" id="department" class="form-control" required>
                        <option value="">-- Select Department --</option>
                        <option value="admin" <?= $department === 'admin' ? 'selected' : '' ?>>Administration</option>
                        <option value="management" <?= $department === 'management' ? 'selected' : '' ?>>Management</option>
                        <option value="operations" <?= $department === 'operations' ? 'selected' : '' ?>>Operations / Fleet</option>
                        <option value="procurement" <?= $department === 'procurement' ? 'selected' : '' ?>>Procurement</option>
                        <option value="maintenance" <?= $department === 'maintenance' ? 'selected' : '' ?>>Maintenance</option>
                        <option value="customer_service" <?= $department === 'customer_service' ? 'selected' : '' ?>>Customer Service</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="role">Role <span class="text-danger">*</span></label>
                    <select name="role" id="role" class="form-control" required>
                        <option value="">-- Select Role --</option>
                        <option value="system_admin" <?= $role === 'system_admin' ? 'selected' : '' ?>>System Administrator</option>
                        <option value="fleet_manager" <?= $role === 'fleet_manager' ? 'selected' : '' ?>>Fleet Manager</option>
                        <option value="procurement_officer" <?= $role === 'procurement_officer' ? 'selected' : '' ?>>Procurement Officer</option>
                        <option value="maintenance_supervisor" <?= $role === 'maintenance_supervisor' ? 'selected' : '' ?>>Maintenance Supervisor</option>
                        <option value="customer_service_staff" <?= $role === 'customer_service_staff' ? 'selected' : '' ?>>Customer Service Staff</option>
                        <option value="mechanic" <?= $role === 'mechanic' ? 'selected' : '' ?>>Mechanic</option>
                        <option value="viewer" <?= $role === 'viewer' ? 'selected' : '' ?>>Viewer / Guest</option>
                        <option value="qr_scanner" <?= $role === 'qr_scanner' ? 'selected' : '' ?>>QR Scanner (Device)</option>
                    </select>
                </div>
            </div>

            <div class="form-group" style="margin-top: var(--space-6);">
                <label class="form-checkbox-label">
                    <input type="checkbox" name="must_change" <?= (!isset($_POST['csrf_token']) || isset($_POST['must_change'])) ? 'checked' : '' ?>> Force password change on first login
                </label>
            </div>
        </div>

        <div class="card-footer-actions">
            <a href="user-management.php" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary">Create User Account</button>
        </div>
    </form>
<script>
function togglePassword(id, iconId) {
    const input = document.getElementById(id);
    const icon = document.getElementById(iconId);
    if (input.type === 'password') {
        input.type = 'text';
        icon.setAttribute('data-lucide', 'eye-off');
    } else {
        input.type = 'password';
        icon.setAttribute('data-lucide', 'eye');
    }
    lucide.createIcons();
}

function generateEmployeeId() {
    const year = new Date().getFullYear();
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let rand = '';
    for (let i = 0; i < 4; i++) {
        rand += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    document.getElementById('employee_id').value = `EMP-${year}-${rand}`;
}
</script>

<?php require_once '../../includes/footer.php'; ?>