-- ============================================================
-- Migration 009: QR Scanner Role
-- Applied: 2026-04-14
-- ============================================================
-- The qr_scanner role is stored as a plain VARCHAR value in
-- users.role — no schema change is required because the column
-- already accepts variable-length strings.
--
-- This migration documents the role and provides optional SQL
-- to create shared scanner accounts for shared tablets/devices.
-- ============================================================

-- Verify the users.role column accepts arbitrary values (informational):
-- SHOW COLUMNS FROM users LIKE 'role';

-- ── Optional: create a shared QR scanner account for a shared workshop tablet ─
-- Uncomment, replace the bcrypt hash, and run once.
-- Generate hash with: php -r "echo password_hash('ChangeMe123!', PASSWORD_BCRYPT, ['cost' => 12]);"
/*
INSERT INTO users
    (employee_id, username, email, password_hash,
     first_name, last_name, role, department, status, must_change_password)
VALUES
    ('QRS-001',
     'qr.scanner',
     'scanner@gensancarrental.com',
     '$2y$12$REPLACE_THIS_WITH_A_REAL_BCRYPT_HASH',
     'QR',
     'Scanner',
     'qr_scanner',
     'operations',
     'active',
     TRUE);
*/

-- ── Batch-regenerate all QR codes to point to the new vehicle-scan.php URL ─────
-- Run this AFTER deploying vehicle-scan.php to update stored qr_code_data URLs.
-- The actual PNG files will be regenerated by run_qr_regeneration.php (see docs).
-- ── Verify: count vehicles with old-style admin QR URLs ─────────────────────
SELECT COUNT(*) AS old_qr_count
FROM vehicles
WHERE qr_code_data LIKE '%vehicle-details.php%'
  AND deleted_at IS NULL;
