<?php
/**
 * Generic Report PDF/HTML Template
 */
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        <?= htmlspecialchars($reportTitle) ?>
    </title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            color: #333;
        }

        h1 {
            font-size: 18px;
            color: #111;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 8px;
            border: 1px solid #ddd;
            text-align: left;
        }

        th {
            background: #f9fafb;
            font-weight: bold;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #666;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <h1>
        <?= htmlspecialchars($reportTitle) ?>
    </h1>
    <p><strong>Date Range:</strong>
        <?= htmlspecialchars($dateFrom) ?> to
        <?= htmlspecialchars($dateTo) ?>
    </p>

    <?php if (empty($data)): ?>
        <p>No data found for this period.</p>
    <?php else: ?>
        <table>
            <thead>
                <tr>
                    <?php
                    // Auto-generate columns based on first row keys
                    $keys = array_keys(is_array($data[0]) ? $data[0] : (array) $data[0]);
                    foreach ($keys as $k): ?>
                        <th>
                            <?= ucwords(str_replace('_', ' ', $k)) ?>
                        </th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $row): ?>
                    <tr>
                        <?php foreach ((array) $row as $val): ?>
                            <td>
                                <?= htmlspecialchars((string) ($val ?? '')) ?>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

    <div class="footer">
        Generated by Gensan Car Rental System &copy;
        <?= date('Y') ?> |
        <?= date('Y-m-d H:i:s') ?>
    </div>
</body>

</html>